spring:
  application:
    name: jobs-api
  data:
    elasticsearch:
      cluster-name: docker-es-cluster
      cluster-nodes: ${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9300}
  elasticsearch:
    rest:
      uris: http://${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_REST_PORT:9200}

okta:
  oauth2:
    issuer: https://${OKTA_DOMAIN}/oauth2/default
    clientId: ${OKTA_CLIENT_ID}
    rolesClaim: groups

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

number-of-fake-jobs: 100

logging:
  level:
    org.springframework.data.elasticsearch.core: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
