spring:
  application:
    name: jobs-api
  data:
    elasticsearch:
      cluster-name: docker-es-cluster
      cluster-nodes: ${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9300}

okta:
  oauth2:
    issuer: https://${OKTA_DOMAIN}/oauth2/default
    clientId: ${OKTA_CLIENT_ID}
    rolesClaim: groups

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
